export {default as Header} from './Header'
export {default as Highlight} from './Highlight'
export {default as Main} from './Main'
export {default as PopularSales} from './PopularSales'
export {default as TopRated} from './TopRated'